##
nameOverride: ""

## Override the deployment namespace
##
namespaceOverride: ""

## Provide a k8s version to auto dashboard import script example: kubeTargetVersionOverride: 1.26.6
##
kubeTargetVersionOverride: ""

## Allow kubeVersion to be overridden while creating the ingress
##
kubeVersionOverride: ""

## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""

commonLabels: {}

## Enable the creation of modules

indigoIam:
  enabled: true
  replicaCount: 1
  image:
    repository: indigoiam/iam-login-service
    tag: v1.8.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  expose:
    enabled: false
  labels: {}
  serviceAccount:
    create: true
    name: my-service-account
    annotations: {  }
