##
nameOverride: ""

## Override the deployment namespace
##
namespaceOverride: ""

## Provide a k8s version to auto dashboard import script example: kubeTargetVersionOverride: 1.26.6
##
kubeTargetVersionOverride: ""

## Allow kubeVersion to be overridden while creating the ingress
##
kubeVersionOverride: ""

## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""

commonLabels: {}

## Enable the creation of modules

indigoIam:
  enabled: true
  replicaCount: 1
  containerPort: 8080
  host: dev.iam.io
  image:
    repository: indigoiam/iam-login-service
    tag: v1.8.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources: #change the resources accordingly
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  expose:
    enabled: false
    use: ingress
  db:
    host: "iam-mysql.default.svc.cluster.local"
    port: 3306
    name: iam
    username: root #change it to non-root user
    password: root
  labels: {}
  serviceAccount:
    enabled: false
    create: true
    name: indigo
    annotations: { }

mysql:
  auth:
    rootPassword: root
    password: password
    database: indigoiam
    username: indigoiam
