---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iam-keystore-config
data:
{{ ($.Files.Glob "static/indigo-iam/*.jwks").AsConfig | indent 2 }}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iam-config
data:
  IAM_PORT: "{{ .Values.indigoIam.containerPort }}"
  IAM_DB_HOST: {{ .Values.indigoIam.db.host }}
  IAM_DB_PORT:  "{{ .Values.indigoIam.db.port }}"
  IAM_DB_NAME:  {{ .Values.indigoIam.db.name }}
  IAM_DB_USERNAME: {{ .Values.indigoIam.db.username }}
  IAM_DB_PASSWORD: {{ .Values.indigoIam.db.password }}
  IAM_JAVA_OPTS: -Dspring.profiles.active=prod,registration,oidc,saml -Dspring.datasource.url=jdbc:mysql://${IAM_DB_HOST}:${IAM_DB_PORT:3306}/${IAM_DB_NAME:iam}?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true -Djava.security.egd=file:/dev/./urandom -Dlogging.level.it.infn.mw=DEBUG
  IAM_HOST: {{ .Values.indigoIam.host }}
  IAM_BASE_URL: http://{{ .Values.indigoIam.host }}:8080 
  IAM_ISSUER: http://{{ .Values.indigoIam.host }}:8080
  IAM_FORWARD_HEADERS_STRATEGY: native
  IAM_KEY_STORE_LOCATION: file:/keystore/keystore.jwks
  IAM_X509_CAN_LOGIN: "true"
  IAM_LOG_LEVEL: DEBUG
  ## SMTP mail server settings 
  IAM_MAIL_HOST: "smtp.mail.internal"  # SMTP server hostname 
  IAM_MAIL_PORT: "25"   # SMTP server port 
  IAM_MAIL_USERNAME: ""   # SMTP server username
  IAM_MAIL_PASSWORD: ""   # SMTP server password