apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: iam-ingress
spec:
  parentRefs:
    - name: gateway
  hostnames:
    iamHost: "iam.local.io"
  rules:
    - matches:
        - path:
            type: Prefix
            value: /
      forwardTo:
        - serviceName: iam
          port: 8080
