{{- if and .Values.indigoIam.enabled .Values.indigoIam.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.indigoIam.serviceAccount.name | default (include "indigo-iam.fullname" .) }}
  annotations:
    {{- toYaml .Values.indigoIam.serviceAccount.annotations | nindent 4 }}
{{- end -}}
